package entities;
// Generated 22 janv. 2019 10:44:26 by Hibernate Tools 3.4.0.CR1


import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Hotel generated by hbm2java
 */
@Entity
@Table(name="hotel"
    ,catalog="mabase"
)
public class Hotel  implements java.io.Serializable {


     private int idhotel;
     private String nomhotel;
     private String adresse;
     private String tel;
     private Set<Reservation> reservations = new HashSet<Reservation>(0);

    public Hotel() {
    }

	
    public Hotel(int idhotel) {
        this.idhotel = idhotel;
    }
    public Hotel(int idhotel, String nomhotel, String adresse, String tel, Set<Reservation> reservations) {
       this.idhotel = idhotel;
       this.nomhotel = nomhotel;
       this.adresse = adresse;
       this.tel = tel;
       this.reservations = reservations;
    }
   
     @Id 

    
    @Column(name="idhotel", unique=true, nullable=false)
    public int getIdhotel() {
        return this.idhotel;
    }
    
    public void setIdhotel(int idhotel) {
        this.idhotel = idhotel;
    }

    
    @Column(name="nomhotel")
    public String getNomhotel() {
        return this.nomhotel;
    }
    
    public void setNomhotel(String nomhotel) {
        this.nomhotel = nomhotel;
    }

    
    @Column(name="adresse")
    public String getAdresse() {
        return this.adresse;
    }
    
    public void setAdresse(String adresse) {
        this.adresse = adresse;
    }

    
    @Column(name="tel")
    public String getTel() {
        return this.tel;
    }
    
    public void setTel(String tel) {
        this.tel = tel;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="hotel")
    public Set<Reservation> getReservations() {
        return this.reservations;
    }
    
    public void setReservations(Set<Reservation> reservations) {
        this.reservations = reservations;
    }




}


